# In this notebook, we're going to cover some of the most fundametal concepts of tensors using TensorFlow

More specfically, we're going to cover:
* Introduction to tensor
* Getting information from tensor
* Manipulating tensors
* Tensor and numpy
* Using `@tf.function`(a way to speed up our regular Python functions)
* Using GPUs with TensorFlow(or TPUs)

## Introduction to tensor

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.11.0


In [2]:
# Create tensor with tf.constant()
scalar = tf.constant(7)
scalar 

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the dimension of a tensor
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of vector
vector.ndim

1

In [6]:
# Create a matrix
matrix = tf.constant([[1,2],
                      [3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [7]:
matrix.shape,matrix.ndim,matrix.dtype

(TensorShape([2, 2]), 2, tf.int32)

In [8]:
# Create another matrix
another_matrix = tf.constant([[1,2,3],
                              [4,5,6],
                              [5,6,7]],dtype=tf.float16)

another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [5., 6., 7.]], dtype=float16)>

In [9]:
# Shape of matrix
another_matrix.shape

TensorShape([3, 3])

In [10]:
# Let's create a tensor
tensor_1_3_3 = tf.constant([
    [
      [1,2,3],
      [2,3,4],
      [3,4,5]

    ]
])

tensor_1_3_3.shape

TensorShape([1, 3, 3])

In [11]:
tensor_2_3_3 = tf.constant([
    [
      [1,2,3],
      [2,3,4],
      [3,4,5]

    ],
    [
        [2,3,4],
        [1,1,1],
        [3,3,3]
    ]
])

tensor_2_3_3.shape

TensorShape([2, 3, 3])

In [12]:
tensor_2_3_3.ndim

3

What we've created so far:

1. Scalar: a single number.
2. Vector: a number with direction(e.g. wind speed and direction)
3. Matrix: a 2-dimension array of numbers
4. Tensor: an n-dimensional array of numbers(when n can be any number, a 0-dimensional tensor is a scalar,a 1-dimension tensor is a vector)


### Creating tensor with `tf.variable`

In [13]:
# Create the same tensor with tf.variable() as above
changeble_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeble_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Let's try change one of the elements in our changeble tensor
changeble_tensor[0]=3
changeble_tensor

TypeError: ignored

In [15]:
# try .assign()
changeble_tensor[0].assign(3)
changeble_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 7], dtype=int32)>

In [16]:
# Let's try change our unchangeble_tensor
unchangeable_tensor[0] = 3
unchangeable_tensor

TypeError: ignored

In [17]:
# try .assign()
unchangeable_tensor[0].assign(3)
unchangeable_tensor

AttributeError: ignored

### Creating random tensors

Random tensors are tensors of some arbitary size which contain random numbers.

In [18]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(128)
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(128)
random_2 = random_2.normal(shape=(3,2))

random_1,random_2,random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.24483992,  0.37554732],
        [ 1.6184237 ,  0.34223038],
        [-0.3702979 , -0.99169385]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.24483992,  0.37554732],
        [ 1.6184237 ,  0.34223038],
        [-0.3702979 , -0.99169385]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of element in a tensor

In [19]:
# Shuffle a tensor (variable for when we want to shuffle our data so the inherent oreder doesn't effect learning)
not_shuffled = tf.constant([[10,1],
                            [2,3],
                            [44,55]
                            ])

# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[44, 55],
       [10,  1],
       [ 2,  3]], dtype=int32)>

In [20]:
# Shuffle our non-shuffled tensor
tf.random.set_seed(128)
tf.random.shuffle(not_shuffled,seed = 128)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[44, 55],
       [10,  1],
       [ 2,  3]], dtype=int32)>

### Other way to make tensors

In [21]:
# Create a tensor of all ones
tf.ones([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [22]:
# Create a tensor of all zeros
tf.zeros([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

 ### Turn NumPy arrays into tensors

 The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU(much faster for numerical computing)

In [23]:
# create a numpy array
import numpy as np

numpy_arr = np.arange(1,9,dtype=np.int32)
numpy_arr

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

In [24]:
numpy_to_tensor = tf.constant(numpy_arr)
numpy_to_tensor

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [25]:
numpy_to_tensor_change_shape = tf.constant(numpy_arr,
                                           shape=(2,2,2))

numpy_to_tensor_change_shape

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

### Geting information from tensors

when dealing with tensors we probably want to be aware of the follow:

* Shape
* Rank
* Axis or dimension
* Size

In [26]:
# Create a rank 4 tensors(4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [27]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [28]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


### Indexing tensors

Tensors can be indexed just like Python lists.

In [29]:
# Get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [30]:
# Get the dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:

# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [32]:
rank_2_tensor.shape

TensorShape([2, 2])

In [33]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[:,:,tf.newaxis] # or rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [34]:
rank_3_tensor.shape

TensorShape([2, 2, 1])

In [35]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis = -1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [36]:
tf.expand_dims(rank_2_tensor,axis = 0) # expand the 0 th axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensor opearation)

**Basic Opearations**

`+,-,*,/`

In [37]:
# we can add values to a tensor using the addition opearator
tensor = tf.constant([[10,12],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 22],
       [13, 14]], dtype=int32)>

In [38]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 12],
       [ 3,  4]], dtype=int32)>

In [39]:
# Multiplication
tensor *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 120],
       [ 30,  40]], dtype=int32)>

In [40]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0,  2],
       [-7, -6]], dtype=int32)>

In [41]:
# We can use the tensorflow built-in function too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 120],
       [ 30,  40]], dtype=int32)>

### Matrix multiplication

One of the most common operations in machine learning algorithms is matrix multiplication.

TensorFlow implements this matrix multiplication functionality in the tf.matmul() method.

In [42]:
# Matrix multiplication in TensorFlow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10 12]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[136, 168],
       [ 42,  52]], dtype=int32)>

In [43]:
# Matrix multiplication with Python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[136, 168],
       [ 42,  52]], dtype=int32)>

In [44]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [45]:
# Try to matrix multiply them (will error)
X @ Y

InvalidArgumentError: ignored

In [46]:
# Example of reshape (3, 2) -> (2, 3)
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [47]:

# Try matrix multiplication with reshaped Y
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [48]:
# Example of transpose (3, 2) -> (2, 3)
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [49]:

# Try matrix multiplication 
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [50]:
# You can achieve the same result with parameters
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot product**

Matrix multiplication is also referred to as the dot product.

we can perform matrix multiplication using:

* `tf.matmul()`
* `tf.tensordot()`

In [57]:
print(f"Shape of X:{X.shape}")
print(f"Shape of Y:{Y.shape}")

Shape of X:(3, 2)
Shape of Y:(3, 2)


In [59]:
tf.transpose(X).shape

TensorShape([2, 3])

In [61]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [62]:
# Perform the dot product on X and Y (requires X to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [52]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [53]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [54]:
# Check shapes of Y, reshaped Y and tranposed Y
Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [55]:
# Check values of Y, reshape Y and tranposed Y
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


### Changing the datatype of a tensor one form to another using `tf.cast()`

In [63]:
# Create a new tensor with default datatype(flot32)
B = tf.constant([1.7,7,4])
B.dtype

tf.float32

In [64]:
C = tf.constant([1,2])
C.dtype

tf.int32

Today, most models use the float32 dtype, which takes 32 bits of memory. However, there are two lower-precision dtypes, float16 and bfloat16, each which take 16 bits of memory instead. **Modern accelerators can run operations faster in the 16-bit dtypes, as they have specialized hardware to run 16-bit computations and 16-bit dtypes can be read from memory faster**.

In [66]:
# Change from float32 to float16 (reduce precision)
D = tf.cast(B,dtype=tf.float16)
D,D.dtype

(<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1.7, 7. , 4. ], dtype=float16)>,
 tf.float16)

In [67]:
# Change from int32 to float32
E = tf.cast(C,dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

### Aggregating Tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [68]:
import tensorflow as tf

In [69]:
val = tf.constant([-1,-3])

In [70]:
# Get the absolute values
tf.abs(val)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

from tensorflow.python.ops.math_ops import maximum
Some of the Aggregation function are:

* Get the maximum
* Get the minimum
* Get the mean of a tensor
* Get the sum of a tensor

In [74]:
E = tf.constant(np.random.randint(0,100,size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([28, 28, 36, 17, 68, 10, 97, 80, 37, 85, 18, 40, 58, 98,  0, 76, 47,
        2, 46, 79, 97, 85, 26, 21, 15, 47, 63, 42, 30, 19, 21, 34, 11, 66,
       63, 49, 35, 60, 72, 53, 66, 96, 11, 15, 97, 27, 52, 26, 45, 11])>

In [76]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [77]:
# Find the Minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [78]:
# Find the Maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [79]:
# Find the average
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [80]:
# Find the Sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2305>

In [87]:
# Find the variance of tensor
print(tf.math.reduce_variance(tf.cast(E,dtype=tf.float32), axis=0))

# Or we can use tensorflow_probability library to calculate varience
import tensorflow_probability as tfp 
print(tfp.stats.variance(E))

tf.Tensor(785.6099, shape=(), dtype=float32)
tf.Tensor(785, shape=(), dtype=int64)


In [88]:
# Find the standerd deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32), axis=0)

<tf.Tensor: shape=(), dtype=float32, numpy=28.028734>

### Find the positional maximum and minimum


In [89]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [91]:
# Find the positional maximum
print(tf.argmax(F))

F[tf.argmax(F)]

tf.Tensor(42, shape=(), dtype=int64)


<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [93]:
# Check for max equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [92]:
# Find the positional minimum
print(tf.argmin(F))

F[tf.argmin(F)]

tf.Tensor(16, shape=(), dtype=int64)


<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [94]:
# Check for max equality
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor(removing all single dimensions)

In [95]:
tf.random.set_seed(128)
val = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
val

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.18266475, 0.2742294 , 0.19852245, 0.04873109, 0.32291985,
           0.7065027 , 0.7153021 , 0.91745734, 0.01603568, 0.26542962,
           0.4423263 , 0.0554235 , 0.28087926, 0.36023653, 0.65006423,
           0.07928371, 0.8757992 , 0.72379637, 0.4249965 , 0.25197792,
           0.35346246, 0.75861526, 0.73074853, 0.5116017 , 0.19794953,
           0.27563298, 0.3316164 , 0.58931303, 0.16800606, 0.4544773 ,
           0.76874447, 0.1638515 , 0.9633399 , 0.51656556, 0.6344831 ,
           0.5638133 , 0.84422493, 0.43629408, 0.65629494, 0.78357065,
           0.20854986, 0.30898583, 0.3393346 , 0.09902024, 0.35783696,
           0.25835204, 0.99178326, 0.08002281, 0.84720874, 0.17835867]]]]],
      dtype=float32)>

In [96]:
val.shape

TensorShape([1, 1, 1, 1, 50])

In [97]:
val_squeezed= tf.squeeze(val)
print(f"Befor squeeze shape is: {val.shape}")
print(f"After Squeeze shape is: {val_squeezed.shape}")

Befor squeeze shape is: (1, 1, 1, 1, 50)
After Squeeze shape is: (50,)


### One hot encoding tensors

In [98]:
# create a list of indices
some_list = [0,1,2,3]

# One hot encode our list of indices
tf.one_hot(some_list,depth=5)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

### Squaring,log,square root

In [99]:
# Create a new tensor
val = tf.range(1,10)
val

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [100]:
# Square it
tf.square(val)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [101]:
# Find the square-root
tf.sqrt(tf.cast(val,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [102]:
# Find the log
tf.math.log(tf.cast(val,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

In [103]:
# Create a tensor directly from a NumPy array
arr = tf.constant(np.array([1.0,2.0,3.0]))
arr

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [105]:
# convert our tensor back to numpy array
np.array(arr),type(np.array(arr))

(array([1., 2., 3.]), numpy.ndarray)

In [106]:
# Convert tensor arr to Numpy array
arr.numpy(),type(arr.numpy())

(array([1., 2., 3.]), numpy.ndarray)

In [107]:
# The default types of each are slightly different
numpy_arr = tf.constant(np.array([3.0,4.0,6.0]))
tensor_arr = tf.constant([3.0,4.0,6.0])

# Check the datatypes of each
numpy_arr.dtype,tensor_arr.dtype

(tf.float64, tf.float32)